version: '3.8'

services:
  # Serviço do PHP
  appvini:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-appvini
    container_name: laravel-appvini
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: appvini
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # Servidor Web (Nginx)
  webservervini:
    image: nginx:alpine
    container_name: laravel-webservervini
    restart: unless-stopped
    ports:
      - "8081:81"
    volumes:
      - .:/var/www
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  # Banco de Dados (MySQL)
  dbvini:
    image: mysql:8.0
    container_name: laraveltrabalhovini
    restart: unless-stopped
    ports:
      - "33062:3307"
    environment:
      MYSQL_DATABASE: bancovini
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local